experiment:
  name: "First lgbm"
run:
  name: "gbdt knn imputation strategy"
algorithm:
  training_algorithm: "gbdt"
imputation:
  strategy: "mean"
  fill_value: null
path:
  input_path: "data/raw/hospitalA_Not_Imputed.csv"
  test_path: "data/raw/Test_Ids.csv"
  train_path: "data/raw/Train_Ids.csv"
